nodes = [
  'ipfs-00',
  'ipfs-01',
  'ipfs-02',
  'ipfs-03',
  'ipfs-04',
  'ipfs-05',
  'ipfs-06',
  'ipfs-07',
  'ipfs-08',
  'ipfs-09',
  'ipfs-10',
  'ipfs-11',
]

links = [
  ['ipfs-00', 'ipfs-01'],
  ['ipfs-00', 'ipfs-02'],
  ['ipfs-01', 'ipfs-03'],
  ['ipfs-01', 'ipfs-04'],
  ['ipfs-02', 'ipfs-04'],
  ['ipfs-02', 'ipfs-05'],
  ['ipfs-03', 'ipfs-06'],
  ['ipfs-04', 'ipfs-06'],
  ['ipfs-04', 'ipfs-07'],
  ['ipfs-05', 'ipfs-07'],
  ['ipfs-05', 'ipfs-08'],
  ['ipfs-06', 'ipfs-09'],
  ['ipfs-07', 'ipfs-09'],
  ['ipfs-07', 'ipfs-10'],
  ['ipfs-08', 'ipfs-10'],
  ['ipfs-09', 'ipfs-11'],
  ['ipfs-10', 'ipfs-11'],
]
